// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using WTSBackend.Persistence;

namespace WTSBackend.Migrations
{
    [DbContext(typeof(WTSContext))]
    partial class WTSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WTSBackend.Models.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Nomenclature");

                    b.HasKey("ID");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("WTSBackend.Models.CorrespondenceType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Flowtime");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.ToTable("CorrespondenceTypes");
                });

            modelBuilder.Entity("WTSBackend.Models.Employee", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BranchID");

                    b.Property<string>("Name");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WTSBackend.Models.Record", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Applicant");

                    b.Property<string>("AssignedTo");

                    b.Property<string>("Branch");

                    b.Property<string>("Comments");

                    b.Property<string>("CorrespondenceType");

                    b.Property<int>("Counter");

                    b.Property<string>("Deadline");

                    b.Property<string>("Subject");

                    b.Property<string>("WTSNumber");

                    b.HasKey("ID");

                    b.ToTable("Records");
                });

            modelBuilder.Entity("WTSBackend.Models.Employee", b =>
                {
                    b.HasOne("WTSBackend.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
